### ISSUE TITLE
数据错位，请修改方法

### ISSUE THREAD

**Issue by lhl-012** [cyixlq/AddressPickerDialog#1]
changeSelect中最后有2个notifyItemChange()
此处会造成数据错误，修改为notifyDataSetChanged（）可解决

**Comment by lhl-012** [comment]
bug出现具体过程 第一和tab选择某项   然后再切换到第一个tab点另外一个  会发现数据中倒数第二第二可能会是第一个tab选中时候的数据，这时候的数据源是没问题的，应该是item没有刷新到

**Comment by cyixlq** [comment]
谢谢指出，不过这个只作为demo展示，提供大家一种思路
